config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "flats#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    if @flat.save
      redirect_to flats_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :number_of_guests, :price_per_night)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_flat.html.erb
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="https://cdn.sanity.io/images/v48q37k7/production/d09208183125ab47493d5de2f8710b6faa27d7cc-3000x2000.jpg" alt="Card image cap">
  <div class="card-body">
    <div>
      <h5 class="card-title"><%= flat.name %></h5>
      <p class="card-text"><%= flat.address %></p>
      <div class="d-flex gap-3">
        <div>
          <i class="fa-solid fa-person"></i>
          <%= flat.number_of_guests %>
        </div>
        <div>
          <i class="fa-solid fa-euro-sign"></i>
          <%= flat.price_per_night %>
        </div>
      </div>
    </div>
    <div class="d-flex bg-light">

    </div>
  </div>
</div>

app/views/flats/_simple_form.html.erb
<%= simple_form_for flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :number_of_guests, as: :numeric %>
  <%= f.input :price_per_night, as: :numeric%>
  <%= f.button :submit %>
<% end %>

app/views/flats/index.html.erb
<div class="container mt-5">
  <h1>All our Flats</h1>
  <p>All our <%= @flats.count %> flats</p>
  <div class="d-flex flex-wrap gap-5" id="flats">
    <% @flats.each do |flat| %>
      <%= render flat %>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container mt-5">
<h1 class="mb-4">New flat</h1>
<%= render "simple_form", flat: @flat %>
</div>

app/views/flats/show.html.erb
<div class="banner">
</div>
<div class="container">
  <div class="row">
    <div class="col-8">
      <div class="card-infos">
        <h1><%= @flat.name %></h1>
        <p><%= @flat.address %></p>
      </div>
      <div class="map-container">
        <h3>A bit more about this flat</h3>
        <p><%= @flat.description %></p>
        <div class="map">
          <img src="https://media.wired.com/photos/59269cd37034dc5f91bec0f1/master/pass/GoogleMapTA.jpg" alt="map">
        </div>
      </div>
    </div>
    <div class="col-4">
      One of three columns
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Simple Airbnb</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        <%= link_to "Add a flat", new_flat_path, class:"btn btn-outline-primary m-2" %>
      </div>
    </div>
    </nav>


    <%= yield %>
  </body>
</html>